#######################################
# Made by João Pedro Vicente Pansiere #
#######################################
version: "3.1"
services:
  webserver:
    image: "nginx:alpine"
    container_name: nginx
    working_dir: /application
    volumes:
      - ".:/application"
      - "./phpdocker.io/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    networks:
      environment_network:
        ipv4_address: 172.30.0.2

  php-fpm:
    build: phpdocker.io/php-fpm
    container_name: php
    working_dir: /application
    volumes:
      - ".:/application"
      - "./phpdocker.io/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini"
    networks:
      environment_network:
        ipv4_address: 172.30.0.3

networks:
  environment_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
